import type { APIRoute } from "astro";

/**
 * /robots.txt — allow all, agents welcome, points at the sitemap.
 *
 * Generated rather than dropped in `public/` so the sitemap URL is built from
 * `site` and cannot fall out of sync with the deployed origin.
 *
 * Points at `/sitemap.xml` (generated by `src/pages/sitemap.xml.ts`), which is the
 * path the SEO baseline requires. Starlight also publishes its own
 * `/sitemap-index.xml` and links it via `rel="sitemap"`; both list the same routes.
 */
export const GET: APIRoute = ({ site }) => {
  if (!site) {
    throw new Error(
      "`site` must be set in astro.config.mjs — robots.txt needs it for an absolute Sitemap URL.",
    );
  }

  const body = `${[
    "# rackctl docs — https://docs.rackctl.sh",
    "# Agents welcome. A machine-readable summary lives at /llms.txt.",
    "",
    "User-agent: *",
    "Allow: /",
    "",
    `Sitemap: ${new URL("/sitemap.xml", site).href}`,
  ].join("\n")}\n`;

  return new Response(body, {
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
};
